executors:
  default: # デフォルトのDockerイメージ
    docker:
      - image: circleci/node:12.13.1
    working_directory: ~/repo

version: 2.1
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Nodeモジュールのインストール
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules

  test_jest:
    parallelism: 2
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Jestを並列実行
          command: |
            TESTFILES=$(circleci tests glob "__tests__/*.ts" | \
            circleci tests split)
            npx jest --ci --maxWorkers=2 \
            $TESTFILES

workflows:
  version: 2
  build_test:
    jobs:
      - setup
      - test_jest:
          requires: # setup のあとに実行
            - setup
